# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# example of config https://jupyterbook.org/en/stable/customize/config.html
title: ߞߎߞߎߞߊ߲
author: ߡߏߙߌ ߞߋߌߕߊ
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# execute:
#   execute_notebooks: force
#   kernel: "my_kernel"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css
  theme:
    name: "sphinx_book_theme"  # Specify a theme that supports customization
    options:
      use_issues: true          # Enable issues on GitHub
      use_readthedocs: true     # Use ReadTheDocs style
  
  

# sphinx config
    
sphinx:
  latex.pdf: true
  timeout: 12000000
  extra_extensions:
    - sphinx_proof
  config:
    bibtex_reference_style: author_year
    html_extra_path: ["resource"]
    html_favicon: favicon.ico
    nb_remove_code_source: true
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    jupyter_sphinx_require_url: "https://unpkg.com/@jupyter-widgets/html-manager@0.18.0/dist/embed-amd.js"

    
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath    

html:
    favicon : "favicon.ico"

execute:
  execute_notebooks: "auto"
  remove_input: true

# extensions:
#   - _extensions.pdf  

  
# execute:
#   execute_notebooks: true  # This ensures that the notebooks are executed during the build process
#   kernel: "my_kernel"  # Use the default kernel across all notebooks
#   cache: false  # You can set this to true if you want to cache executed notebooks
    