name: Publish Jupyter Book

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Change to your desired Python version

    - name: Install dependencies
      run: |
        pip install jupyter-book ghp-import

    - name: Build the book
      run: |
        jupyter-book build ./  # Change 'mybook/' to your book's directory

    - name: Deploy to GitHub Pages
      run: |
        ghp-import -n -p -f _build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
